// src/lib/components/Hero.svelte
<script>
	let clientW = 0;
</script>

<div
	class="min-h-screen hero bg-base-100"
	style="background-image: url(https://images.unsplash.com/photo-1454496522488-7a8e488e8606?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=compress&fit=crop&w={clientW}&blur=75&monochrome=0C6291&bri=30&con=-30)"
	bind:clientWidth={clientW}
>
	<div class="z-20 flex-col hero-content lg:flex-row-reverse">
		<div>
			<h1 class="py-3 text-6xl font-bold lg:text-9xl">Your business.<br />Our solutions.</h1>
			<div class="max-w-3xl text-xl prose md:text-2xl lg:text-3xl;">
				<p class="mb-5  text-xl prose md:text-2xl lg:text-3xl;">
					Need a partner to help you make the most of web technologies?
				</p>
				<p class="mb-5  text-xl prose md:text-2xl lg:text-3xl;">
					Traist specialises in building bespoke solutions to maximise value across your business.
				</p>
				<button class="text-xl normal-case btn btn-primary">What are you planning?</button>
			</div>
		</div>
	</div>
</div>

// components/hero/Hero.tsx
import Image from 'next/image';
import Button from '../button/Button';

export default function Hero() {
  return (
    <section className="px-4 md:px-24 z-0 flex flex-col flex-grow justify-center overflow-hidden relative bg-gradient-to-br from-brand-50 via-brand-200 to-brand-300">
      <div className="w-1/3 absolute right-0 bottom-2 aspect-h-1 aspect-w-6">
        <Image
          src="/images/mountain.svg"
          alt=""
          role="presentation"
          layout="fill"
        />
      </div>
      <h1 className="font-bold text-6xl md:text-9xl py-3">
        Your business.<br />
      Our solutions.
    </h1>
      <div className="max-w-3xl text-brand-600">
        <p className="py-3 text-3xl">
          Need a partner to help you make the most of web technologies?
      </p>
        <p className="py-3 text-3xl">
          Traist specialises in building bespoke solutions to maximise value
          across your business.
      </p>
        <p className="py-5 text-3xl">
          <Button type="link" href="/learn-more" colour="secondary" size="lg">Learn More</Button>
        </p>
      </div>
    </section>
  )
}
